# -*- coding: utf-8 -*-
"""random_forest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fkecz5ndA8kiU0FJOrv_jiQygpQDO7XK
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
import geojson
import geopandas as gpd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.ensemble import RandomForestClassifier

# ! pip install scikit-learn
# ! pip install geopandas
# ! pip install geojson

# data = gpd.read_file('./classified-21062026-2.geojson')
data = gpd.read_file('./segmentation-waterareas-only.geojson')

data.plot()

data.columns

data.shape

# data.where(data['Classified_as_ship']==0).where(data['Classified_as_water']==0)

# drop classfied_as_water column
df = data.drop('Classified_as_water', axis=1)

# get rid of data points where class is unknown
df_unknown = data.where(data['Classified_as_temp']==1)

# df_ship = pd.concat([df, df_unknown, df_unknown]).drop_duplicates(keep=False)
df = df.drop(df[df['Classified_as_temp']== 1].index)

# separate features to train, and classified_as_ship as the target
# features to train
X = df.loc[:, ~df.columns.isin(['Classified_as_ship','Classified_as_temp', 'geometry'])].values
# correct answers
y = df.loc[:, 'Classified_as_ship'].values

X.shape

df.head()

y.shape

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# feature scaling not so important for RF
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

classifier = RandomForestClassifier(n_estimators=100, random_state=42)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy * 100:.2f}%')

feature_importances = classifier.feature_importances_

plt.barh(df.loc[:, ~df.columns.isin(['Classified_as_ship','Classified_as_temp', 'geometry'])].columns, feature_importances)
plt.xlabel('Feature Importance')
plt.title('Feature Importance in Random Forest Classifier')
plt.show()

y_pred

y_pred.shape

df['pred'] = classifier.predict(X)

df

df.plot(column='pred')

X_unknown = df_unknown.loc[:, ~df_unknown.columns.isin(['Classified_as_ship','Classified_as_temp','Classified_as_water', 'geometry'])].values

df_unknown['pred'] = classifier.predict(X_unknown)

df_unknown

X_all = data.loc[:, ~data.columns.isin(['Classified_as_ship','Classified_as_temp','Classified_as_water', 'geometry'])].values

data['pred'] = classifier.predict(X_all)

data.head()

data.plot(column='Classified_as_ship', figsize=(10,10))

# for tommy

# can the interface produce the ship classifier column through interactivity?
# if so then we can run the RF with those labels

# can there be a list of columns of features displayed?
# then the ones which are ticked go to the X (features) of the RF classifier

# https://www.geeksforgeeks.org/random-forest-classifier-using-scikit-learn/