# -*- coding: utf-8 -*-
"""sahi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JuU0DOEbZY1-mUCT0J6yFGkXFNEKhv0b

# Using SAHI (SLicing Aided Hyper Inference)
"""

!pip install sahi
!pip install ultralytics

import time
from sahi import AutoDetectionModel
from sahi.predict import get_sliced_prediction

# get the model or download it
import os
from datetime import datetime
from ultralytics import YOLO

os.makedirs("models", exist_ok=True)

model = YOLO("models/yolo26m-seg.pt")

for k,v in model.names.items():
    print(f"{k}: {v}")

# print(type(model.names))

image = "port_image.png"
# image = "port_image.png"
image_name_only = image.split(".")[0]
image_extention = image.split(".")[1]

# wrapping the SAM3 model
detection_model = AutoDetectionModel.from_pretrained(
    model_type="ultralytics",
    # model_path="sam3.pt",
    model_path="models/yolo26m-seg.pt",
    device="cuda",
    confidence_threshold=0.25,
)

# Record the start time
start_time = time.time()

result = get_sliced_prediction(
    image,
    detection_model,
    slice_height=640,
    slice_width=640,
    overlap_height_ratio=0.2,  # 20% overlap to handle cross-boundary objects
    overlap_width_ratio=0.2,
    postprocess_type="NMM",  # better for segmentation masks
    postprocess_match_threshold=0.5
)

# targetted_classes = ["boat", "surfboard"]
# filename = f"{image_name_only}-{datetime.now()}.{image_extention}"

# needed_predictions = [item for item in result.object_prediction_list if item.category.name in targetted_classes ]

# result.object_prediction_list  = needed_predictions


# # export only the needed predictions
# result.export_visuals(
#     export_dir="output/",
#     file_name=filename
# )
# Record the end time
end_time = time.time()
execution_time = end_time - start_time
print(f"Function execution time: {execution_time:.4f} seconds")

# Filter out the predictions
targetted_classes = ["boat", "surfboard"]
filename = f"{image_name_only}-{datetime.now()}.{image_extention}"

needed_predictions = [item for item in result.object_prediction_list if item.category.name in targetted_classes ]

result.object_prediction_list  = needed_predictions


# export only the needed predictions
result.export_visuals(
    export_dir="output/",
    file_name=filename
)

print(f"Predictions saved to {filename}")

"""# Export to GeoJSON"""

import json
import geopandas as gpd

# export to geojson
geojson = result.to_coco_annotations()  # not ideal for maps

print(geojson)

import json
import numpy as np
import cv2
import rasterio
from rasterio.transform import xy

class NumpyEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, np.floating): return float(obj)
        if isinstance(obj, np.integer): return int(obj)
        if isinstance(obj, np.ndarray): return obj.tolist()
        return super().default(obj)

# check if image has a CRS
with rasterio.open(image) as src:
    has_crs = src.crs is not None
    transform = src.transform if has_crs else None
    crs = src.crs if has_crs else None
    print(f"CRS found: {crs}" if has_crs else "No CRS — using pixel coordinates")

def pixel_to_geo(row, col, transform):
    """Convert pixel (row, col) to geographic (lon, lat)"""
    lon, lat = xy(transform, row, col)
    return [lon, lat]

features = []
for pred in needed_predictions:
    if pred.mask is not None:
        mask = pred.mask.bool_mask
        contours, _ = cv2.findContours(
            mask.astype(np.uint8),
            cv2.RETR_EXTERNAL,
            cv2.CHAIN_APPROX_SIMPLE
        )
        for contour in contours:
            if len(contour) >= 3:
                points = contour.squeeze()
                if len(points.shape) == 1:
                    continue  # skip degenerate contours

                if has_crs:
                    # pixel (x=col, y=row) - geographic coords
                    coords = [pixel_to_geo(pt[1], pt[0], transform) for pt in points]
                else:
                    # flip y axis for pixel coords (image y is top-down, geojson is bottom-up)
                    img_height = pred.mask.bool_mask.shape[0]
                    coords = [[int(pt[0]), int(img_height - pt[1])] for pt in points]

                coords.append(coords[0])  # close polygon
                features.append({
                    "type": "Feature",
                    "geometry": {"type": "Polygon", "coordinates": [coords]},
                    "properties": {
                        "class": pred.category.name,
                        "confidence": float(pred.score.value)
                    }
                })

geojson_output = {
    "type": "FeatureCollection",
    "crs": {"type": "name", "properties": {"name": str(crs)}} if has_crs else None,
    "features": features
}

with open("output/boats.geojson", "w") as f:
    json.dump(geojson_output, f, cls=NumpyEncoder)

print(f"Exported {len(features)} boat polygons")

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.patches import Polygon
from matplotlib.collections import PatchCollection
import json
import numpy as np
from PIL import Image

# load image
img = np.array(Image.open(image))
img_height, img_width = img.shape[:2]

# load geojson
with open("output/boats.geojson") as f:
    gj = json.load(f)

fig, ax = plt.subplots(1, 1, figsize=(20, 20))
ax.imshow(img)

patches = []
for feature in gj["features"]:
    coords = np.array(feature["geometry"]["coordinates"][0])

    if has_crs:
        # convert geo coords back to pixel for display
        with rasterio.open(image) as src:
            from rasterio.transform import rowcol
            rows, cols = rowcol(src.transform, coords[:, 0], coords[:, 1])
            pixel_coords = np.column_stack([cols, rows])
    else:
        # flip y back for display
        pixel_coords = np.column_stack([coords[:, 0], img_height - coords[:, 1]])

    polygon = Polygon(pixel_coords, closed=True)
    patches.append(polygon)

collection = PatchCollection(
    patches,
    facecolor="cyan",
    edgecolor="red",
    alpha=0.3,
    linewidths=1.5
)
ax.add_collection(collection)

ax.set_title(f"Boat Detections: {len(patches)} found", fontsize=16)
ax.axis("off")
plt.tight_layout()
# plt.savefig("output/boats_overlay.png", dpi=150, bbox_inches="tight")
plt.show()

"""# YOLO segmentation model"""

# Load a model
model = YOLO("yolo26m-sem.pt")  # load an official model

# Predict with the model
results = model("https://ultralytics.com/images/bus.jpg")  # predict on an image


# # Access the results
# for result in results:
#     semantic_mask = result.semantic_mask.data

from IPython.display import Image, display

results[0].save("result.jpg")
display(Image(filename="result.jpg"))