# -*- coding: utf-8 -*-
"""sam3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YbEUYksVvG0ZPCAgwhLi5tFBs_wCQy_i
"""



!pip install ultralytics
!pip install -q huggingface_hub

import os
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"
# must be set BEFORE importing torch

from huggingface_hub import login, hf_hub_download

login(token="huggingface token here")

hf_hub_download(repo_id="facebook/sam3", filename="sam3.pt", local_dir=".")

from ultralytics.models.sam import SAM3SemanticPredictor
import torch

# image = "image_part.tif"
image = "port_image.png"

# Initialize predictor with configuration
overrides = dict(
    conf=0.25,
    task="segment",
    mode="predict",
    model="sam3.pt",
    half=True,  # Use FP16 for faster inference
    imgsz=1024,
    save=True,
)
predictor = SAM3SemanticPredictor(overrides=overrides)

# Set image once for multiple queries
predictor.set_image(image)

torch.cuda.empty_cache()

results = predictor(text=["boat", "ship", "vessel", "watercraft", "a boat on water"])