# -*- coding: utf-8 -*-
"""yolo_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G9GRlWuiqVd7bAVthKCbiU7mYQYyEOEI
"""

!pip install ultralytics

import json
import os
import pathlib

import cv2
import numpy as np
import torch

"""# GEOJSON to YOLO Labels"""

def geojson_to_yolo(geojson_path: str, output_label_dir: str) -> dict:
    """
    Convert a GeoJSON FeatureCollection with pixel-coordinate polygons into
    YOLO segmentation .txt label files.

    Returns the class_map used (name to int id).
    """
    with open(geojson_path) as f:
        gj = json.load(f)

    meta = gj["metadata"]
    W, H = meta["image_width"], meta["image_height"]
    image_stem = pathlib.Path(meta["image"]).stem

    # Build class map from the registry in the GeoJSON
    class_map = {c["id"]: i for i, c in enumerate(meta["class_registry"])}
    name_map  = {c["id"]: c["name"] for c in meta["class_registry"]}

    os.makedirs(output_label_dir, exist_ok=True)

    lines = []
    for feat in gj["features"]:
        cid    = class_map[feat["properties"]["class_id"]]
        coords = feat["geometry"]["coordinates"][0]  # outer ring only

        # Normalise to [0, 1] and flatten: x1 y1 x2 y2
        norm = []
        for x, y in coords:
            norm.append(f"{min(max(x / W, 0), 1):.6f}")
            norm.append(f"{min(max(y / H, 0), 1):.6f}")

        lines.append(f"{cid} " + " ".join(norm))

    label_path = os.path.join(output_label_dir, f"{image_stem}.txt")
    with open(label_path, "w") as f:
        f.write("\n".join(lines))

    print(f"[convert] Wrote {len(lines)} labels to {label_path}")
    return class_map, name_map, W, H


"""# Fine-tune YOLOv8"""

def finetune_yolo(
    yaml_path: str,
    base_model: str = "yolov8n-seg.pt",
    epochs: int = 50,
    imgsz: int = 640,
    project: str = "runs/finetune",
    name: str = "boat_detector",
):
    from ultralytics import YOLO

    model = YOLO(base_model)
    print(f"[finetune] Starting fine-tuning: {base_model} - {project}/{name}")
    result = model.train(
        data=yaml_path,
        epochs=epochs,
        imgsz=imgsz,
        project=project,
        name=name,
        patience=15,
        batch=4,           # small batch for single-image dataset
        workers=2,
        augment=True,      # YOLO's own augmentation on top of albumentations
        cos_lr=True,
        optimizer="AdamW",
        lr0=1e-4,
        lrf=0.01,
        mosaic=0.5,
        degrees=45.0,
        fliplr=0.5,
        flipud=0.5,
    )

    actual_dir = pathlib.Path(result.save_dir)

    best_weights = str(actual_dir / "weights" / "best.pt")
    print(f"[finetune] Done. Best weights: {best_weights}")
    return best_weights

"""# Sliding-window inference + NMS merge"""
def sliding_window_detect(
    image_path: str,
    weights: str,
    tile_size: int = 512,
    overlap: int = 128,
    conf_threshold: float = 0.25,
    nms_iou: float = 0.4,
    target_classes: list = None,   # e.g. [0] to keep only "boat"
    output_path: str = "detections.png",
):
    """
    Run YOLO on overlapping tiles of the full image, collect all bounding
    boxes, then merge overlapping detections with NMS.
    """
    from ultralytics import YOLO
    from torchvision.ops import nms as torch_nms

    model = YOLO(weights)
    img   = cv2.imread(image_path)
    assert img is not None, f"Could not read image: {image_path}"
    H, W  = img.shape[:2]

    stride = tile_size - overlap

    all_boxes, all_scores, all_classes = [], [], []

    tile_count = 0
    for y0 in range(0, H, stride):
        for x0 in range(0, W, stride):
            x1 = min(x0 + tile_size, W)
            y1 = min(y0 + tile_size, H)
            tile = img[y0:y1, x0:x1]

            results = model(tile, conf=conf_threshold, verbose=False)[0]

            for box in results.boxes:
                cls = int(box.cls)
                if target_classes and cls not in target_classes:
                    continue
                bx1, by1, bx2, by2 = box.xyxy[0].tolist()
                # Translate tile-local coords back to full-image coords
                all_boxes.append([bx1 + x0, by1 + y0, bx2 + x0, by2 + y0])
                all_scores.append(float(box.conf))
                all_classes.append(cls)

            tile_count += 1

    print(f"[detect] Processed {tile_count} tiles, found {len(all_boxes)} raw detections")

    if not all_boxes:
        print("[detect] No detections found.")
        cv2.imwrite(output_path, img)
        return output_path

    # NMS across all tiles
    boxes_t  = torch.tensor(all_boxes,  dtype=torch.float32)
    scores_t = torch.tensor(all_scores, dtype=torch.float32)
    keep     = torch_nms(boxes_t, scores_t, iou_threshold=nms_iou)

    final_boxes   = boxes_t[keep].int().tolist()
    final_scores  = scores_t[keep].tolist()
    final_classes = [all_classes[i] for i in keep.tolist()]

    print(f"[detect] {len(final_boxes)} detections after NMS")

    # Draw results
    # Load class names from model if available
    try:
        names = model.names
    except Exception:
        names = {}

    for box, score, cls in zip(final_boxes, final_scores, final_classes):
        x1, y1, x2, y2 = box
        label = f"{names.get(cls, cls)} {score:.2f}"
        cv2.rectangle(img, (x1, y1), (x2, y2), (0, 220, 100), 2)
        cv2.putText(img, label, (x1, max(y1 - 6, 10)),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.45, (0, 220, 100), 1, cv2.LINE_AA)

    cv2.imwrite(output_path, img)
    print(f"[detect] Saved annotated image to {output_path}")
    return output_path

"""# Run Parameters"""

# image = "image_part.tif"
# geojson = "image_part.geojson"

image = "port_image.png"
geojson = "port_image.geojson"

weights = "yolo26m-seg.pt"

tile = 512
overlap = 128

conf = 0.25
iou = 0.4

epochs = 100
augmented = 200

output = "detections"
os.makedirs(output, exist_ok=True)
dataset_dir = "dataset"

"""# GEOJson to YOLO Labels"""

geojson_to_yolo(
    geojson,
    "labels/train"
)

print("Done. Label files written to labels/train/")


"""# Fine-Tune YOLO and Detect

### Fine Tune
"""
yaml_path = "/content/datasets/dataset.yaml"
finetune_yolo(
    yaml_path,
    base_model=weights,
    epochs=epochs,
)

"""## Detect with fine-tuned model"""
best_weights = "/content/runs/segment/runs/finetune/boat_detector/weights/best.pt"

# Run detection using the trained model
sliding_window_detect(
    image,
    best_weights,
    tile_size=tile,
    overlap=overlap,
    conf_threshold=conf,
    nms_iou=iou,
    target_classes=[0],  # boat class in custom dataset
    output_path=os.path.join(output, "detected_fine_tuned.png"),
)

print(f"Detection complete. Output saved to {output}")
print(f"Best model: {best_weights}")

"""# Detection with Pretrained YOLO"""

# sliding_window_detect(
#     image,
#     weights,
#     tile_size=tile,
#     overlap=overlap,
#     conf_threshold=conf,
#     nms_iou=iou,
#     target_classes=[8],  # COCO boat class
#     output_path=os.path.join(output, "detected_pre_trained.png"),
# )
#
# print(f"Detection complete. Output saved to {output}")

from ultralytics import YOLO
import time

model = YOLO(weights)

start_time = time.time()
results = model(image)

results[0].save(filename="boat_detected_pretrained.jpg")

end_time = time.time()
execution_time = end_time - start_time
print(f"Function execution time: {execution_time:.4f} seconds")